<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sqr</string>
	</array>
	<key>name</key>
	<string>PeopleSoft SQR</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments begin with a bang</string>
			<key>match</key>
			<string>(!).*$
?</string>
			<key>name</key>
			<string>comment.block.SQR</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(declare-report)(\s+)([A-Za-z][-A-Za-z0-9_]*)([^-]|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.SQR</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SQR</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend-report\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.SQR</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.report.SQR</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(begin-procedure)(\s+)([A-Za-z][-A-Za-z0-9_]*)([^-]|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.SQR</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.SQR</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\bend-procedure\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.SQR</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.procedure.SQR</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b)*(#)(?i:include)\b</string>
			<key>name</key>
			<string>keyword.include.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$|#)([A-Za-z][A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>variable.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\|\||!=|=|&gt;|&lt;|&gt;=|&lt;=|&lt;&gt;|\+|\^|\*|/|#|%|(\s(-|not|and|or|xor)\s))</string>
			<key>name</key>
			<string>keyword.operator.SQR</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single quoted string</string>
			<key>match</key>
			<string>('(?:\\'|.)*?')</string>
			<key>name</key>
			<string>string.single.source.SQR</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Double quoted string</string>
			<key>match</key>
			<string>(\"(?:\\"|.)*?\")</string>
			<key>name</key>
			<string>string.double.source.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(if|else|end-if|while|end-while)\b)</string>
			<key>name</key>
			<string>keyword.control.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b((begin|end)-(declare|document|evaluate|execute|footing|heading|procedure|program|report|select|setup|sql)|declare-(chart|color-map|connection|image|layout|printer|procedure|report|toc|variable)|exit-select)\b)</string>
			<key>name</key>
			<string>keyword.function.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\s*\b(let)\b\s*)</string>
			<key>name</key>
			<string>storage.type.SQR</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+\b(?i:(add|alter-(color-map|locale|printer|report)|array-(add|divide|multiply|subtract)|ask|break|call|(clear|create)-array|close|columns|commit|concat|connect|create-color-palatte|display|divide|do|encode|evaluate|extract|find|get|get-color|goto|graphic|input|last-page|move|to|use))\b\s+</string>
			<key>name</key>
			<string>support.function.SQR</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.SQR</string>
	<key>uuid</key>
	<string>57919b5d-ed39-4d40-9cce-2dce7935b80b</string>
</dict>
</plist>
